class_name CustomerData
extends Resource

@export_category("General")
@export var name: String
## Which map the customer will be in
@export var spawn_location: GameConstants.Locations 
## Possible artifacts they may commission
@export var owned_artifacts: Array[String]

## Dictates the behaviour of the customer when making comissions.
@export_category("Personality")
## How much they can pay the player for their job
@export_range(0, 3, 0.1) var richness: float  = 1
## An added duration to how long it should take to solve the artifact before the customer comes back to receive
@export_range(0, 5, 1) var patience: int = 3
## Accuracy in determining the runes on a comissioned artifact
@export_range(0, 5, 1) var intelligence: int = 3
## Customer dialogue
@export var dialogue: Dictionary


# Non special customers will be generated by the game
@export_category("Special Characters")
@export var is_special: bool = false
@export_range(0, 5, 1) var favorability: int = 0
@export var special_commissions: Array[CommissionData]


# Attributes assigned to using the data from general and personality
var commission: CommissionData
var return_day: int

# Used to prepare a default and randomized instance of characters based on the location
func prepare_character(location):
	var generic_names = GameConstants.GenericNames
	name = generic_names[randi() % len(generic_names)]
	spawn_location = location
	# TODO: Preparing the artifacts bsed on location
	# TODO: Inserting dialogue
	# TODO: varying values in the personality
	
